language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install

script: 
    - phpunit
    - ! 'php vendor/bin/phpbench run tests/Benchmark --report=''{"name": "console_table", "memory": true, "aggregate_iterations": true, "revolutions" true}'''
